// src\public_app\layout\navbar\navbardesktop\NavbarDesktopData.js
import {
  FaAtom,
  FaFlask,
   FaChevronDown,
  FaDna,
  FaSquareRootAlt,
  FaGlobeAmericas,
  FaHeart,
  FaBook,
  FaChalkboardTeacher,
  FaUserGraduate,
  FaMicroscope,
  FaRocket,
  FaBrain,
  FaLeaf,
  FaStar,
  FaCalculator,
  FaChartLine,
  FaDragon,
  FaUserAstronaut,
  FaVial,
  FaFire,
  FaWind,
  FaTree,
  FaDog,
  FaQuestionCircle,
  FaInfoCircle,
  FaBlog,
  FaNewspaper,
  FaPhone,
  FaEnvelope,
  FaSatellite,
  FaSpaceShuttle,
  FaMeteor,
  FaSeedling,
  FaFish,
  FaBolt,
  FaSun,
  FaGraduationCap,
} from "react-icons/fa";

export const navItems = [
  {
    label: "Home",
    to: "/",
    icon: FaGraduationCap,
    color: "text-blue-600",
  },
  {
    label: "Mathematics",
    to: "/mathematics",
    icon: FaSquareRootAlt,
    color: "text-red-500",
    dropdown: [
      { label: "Algebra", to: "/mathematics/algebra", icon: FaCalculator },
      { label: "Calculus", to: "/mathematics/calculus", icon: FaChartLine },
      { label: "Geometry", to: "/mathematics/geometry", icon: FaDragon },
      { label: "Statistics", to: "/mathematics/statistics", icon: FaChartLine },
      { label: "Trigonometry", to: "/mathematics/trigonometry", icon: FaStar },
      { label: "Number Theory", to: "/mathematics/number-theory", icon: FaStar },
    ],
  },
  {
    label: "Biology",
    to: "/biology",
    icon: FaDna,
    color: "text-green-500",
    dropdown: [
      { label: "Cell Biology", to: "/biology/cell-biology", icon: FaMicroscope },
      { label: "Genetics", to: "/biology/genetics", icon: FaDna },
      { label: "Ecology", to: "/biology/ecology", icon: FaLeaf },
      { label: "Neuroscience", to: "/biology/neuroscience", icon: FaBrain },
      { label: "Evolution", to: "/biology/evolution", icon: FaDragon },
      { label: "Zoology", to: "/biology/zoology", icon: FaDog },
      { label: "Botany", to: "/biology/botany", icon: FaSeedling },
      { label: "Marine Biology", to: "/biology/marine", icon: FaFish },
    ],
  },
  {
    label: "Chemistry",
    to: "/chemistry",
    icon: FaFlask,
    color: "text-purple-500",
    dropdown: [
      { label: "Organic Chemistry", to: "/chemistry/organic", icon: FaLeaf },
      { label: "Inorganic Chemistry", to: "/chemistry/inorganic", icon: FaVial },
      { label: "Physical Chemistry", to: "/chemistry/physical", icon: FaFire },
      { label: "Biochemistry", to: "/chemistry/biochemistry", icon: FaDna },
      { label: "Analytical Chemistry", to: "/chemistry/analytical", icon: FaMicroscope },
      { label: "Polymer Chemistry", to: "/chemistry/polymer", icon: FaDragon },
    ],
  },
  {
    label: "Physics",
    to: "/physics",
    icon: FaAtom,
    color: "text-blue-500",
    dropdown: [
      { label: "Mechanics", to: "/physics/mechanics", icon: FaRocket },
      { label: "Quantum Physics", to: "/physics/quantum", icon: FaAtom },
      { label: "Relativity", to: "/physics/relativity", icon: FaSun },
      { label: "Thermodynamics", to: "/physics/thermodynamics", icon: FaFire },
      { label: "Electromagnetism", to: "/physics/electromagnetism", icon: FaBolt },
      { label: "Nuclear Physics", to: "/physics/nuclear", icon: FaStar },
      { label: "Optics", to: "/physics/optics", icon: FaSun },
    ],
  },
  {
    label: "Astronomy",
    to: "/astronomy",
    icon: FaGlobeAmericas,
    color: "text-orange-500",
    dropdown: [
      { label: "Stars & Constellations", to: "/astronomy/stars", icon: FaStar },
      { label: "Planets", to: "/astronomy/planets", icon: FaGlobeAmericas },
      { label: "Galaxies", to: "/astronomy/galaxies", icon: FaSun },
      { label: "Cosmology", to: "/astronomy/cosmology", icon: FaSpaceShuttle },
      { label: "Observational Astronomy", to: "/astronomy/observational", icon: FaSatellite },
      { label: "Astrophysics", to: "/astronomy/astrophysics", icon: FaMeteor },
      { label: "Solar System", to: "/astronomy/solar-system", icon: FaSun },
    ],
  },
  {
    label: "Sexology",
    to: "/sexology",
    icon: FaHeart,
    color: "text-pink-500",
    dropdown: [
      { label: "Human Sexuality", to: "/sexology/human-sexuality", icon: FaHeart },
      { label: "Sexual Health", to: "/sexology/sexual-health", icon: FaHeart },
      { label: "Psychology", to: "/sexology/psychology", icon: FaBrain },
      { label: "Education", to: "/sexology/education", icon: FaBook },
      { label: "Research", to: "/sexology/research", icon: FaMicroscope },
      { label: "Therapy", to: "/sexology/therapy", icon: FaHeart },
      { label: "Sociology", to: "/sexology/sociology", icon: FaUserGraduate },
    ],
  },

 
  {
    label: "About",
    to: "/about",
    icon: FaInfoCircle,
    color: "text-gray-600",
 
  },
];